### ISSUE TITLE
Conflict with Svelte Material

### ISSUE THREAD

**Issue by ioannist** [alphapeter/fa-svelte#14]
Svelte material requires
import Icon from "@smui/textfield/icon/index";

FA should use another name to avoid pain...

**Comment by wtcross** [comment]
This does not feel painful to me:
`import Icon as MIcon from "@smui/textfield/icon";`

Why should @alphapeter break his API so you can avoid typing a single letter?

**Comment by alphapeter** [comment]
You can choose any variable name you want when there's no "named export". 

```javascript
import FaSvelte from "fa-svelte"
```
or 
```javascript
import Foo from "fa-svelte"
```
The `Icon` variable naming is an example.  

Check the webpack documentation at https://webpack.js.org/api/module-methods/
