### ISSUE TITLE
Question: Is it possible to dynamically import only needed icons? 

### ISSUE THREAD

**Issue by VladimirHumeniuk** [alphapeter/fa-svelte#16]
Is it possible to dynamically import only needed icons? For example, if I don't know which exactly icons will be used in component, and the icons names came as a strings from the server, should I just import all icons like this:
```
import * as icons from '@fortawesome/free-solid-svg-icons/';
```

And then use as:
```
<Icon icon={icons[key]}>
```
?

But i'm afraid in this case I will add to the bundle all FA icons. Is there any solution to do it properly?

Thaks

**Comment by alphapeter** [comment]
I think what you are looking for is called _tree shaking_. The purpose of tree shaking is to _remove_ dead code _afterwards_.

I can't help you with that though since I have no successful experience using it with font awesome icons.

But if you succeed, please share your experience.
