### ISSUE TITLE
How to apply the class fa-spin for faSpinner?

### ISSUE THREAD

**Issue by Bighamster** [alphapeter/fa-svelte#21]
I'd like to have an animated spinner like:

`<i class="fas fa-spinner fa-spin"></i>`

Is it possible?

**Comment by alphapeter** [comment]
Hi! 
You can add your own CSS style for animation. 
Somethink like in https://github.com/alphapeter/fa-svelte/issues/20

Maybe the fa-spin could be include with the ability to toggle with a prop though. Or adding a new component, FaSpin for use with spinning icons.

**Comment by Bighamster** [comment]
Thanks a lot! [#20 ](https://github.com/alphapeter/fa-svelte/issues/20) is great!

I believe that example is worth adding to README ... very useful!
