### ISSUE TITLE
Ref directive no longer supported

### ISSUE THREAD

**Issue by stychu** [alphapeter/fa-svelte#4]
[!] (svelte plugin) ParseError: The ref directive is no longer supported — use `bind:this={icon}` instead

**Comment by alphapeter** [comment]
There are no usages of "ref" in fa-svelte.

You've probably upgraded to svelte 3 and therefore, you need to follow the new API.
https://svelte.dev/docs

The error message tells you how to resolve the issue. Use bind:this instead of ref.
