### ISSUE TITLE
Issue with Duotone

### ISSUE THREAD

**Issue by RemiKalbe** [alphapeter/fa-svelte#6]
If I use the new fontawesome duotone style, only one part on the icon shows.
For example, https://fontawesome.com/icons/money-check?style=duotone
only the part with less opacity will show.

**Comment by RemiKalbe** [comment]
The "classic" styles's svgPathData is a string, but with duotone it's an array of 2 strings.

**Comment by Cweili** [comment]
Have a try [`svelte-fa`](https://github.com/Cweili/svelte-fa)

https://cweili.github.io/svelte-fa/

**Comment by alphapeter** [comment]
Sorry for the late reply!
I noticed that you already found an alternative that fits your needs, perfect!
