### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by wcjr** [alphapeter/fa-svelte#7]
I wasn't sure how to best thank you for putting this repo together, save my team and I at least a day!  Thank you!

**Comment by alphapeter** [comment]
Thanks for the appreciation. 
I keep this library to a bare minimum of funtionality. :)

**Comment by wcjr** [comment]
that's exactly why we chose it:

> "A designer knows he has achieved perfection not when there is nothing left to add, but when there is nothing left to take away."  – Antoine de Saint-Exupery

Great job!
