### ISSUE TITLE
Allow to pass the icon size

### ISSUE THREAD

**Issue by moshfeu** [alphapeter/fa-svelte#8]
Currently, the only option to change the size is to wrap the component with an element and set the `font-size` of it, for example:

```
<style>
  .icon {
    font-size: 30px
  }
</style>
<i class="icon">
  <Icon icon={faGasPump} />
</i>
```

I suggest to allow to pass the size in a prop. Maybe something like this: https://stackoverflow.com/a/57183208/863110

**Comment by alphapeter** [comment]
Hi!
I've noticed that there is another project which supports what you ask for: 
https://cweili.github.io/svelte-fa/

I will currently keep this project as lightweight as possible, just providing the basic functionality for rendering simple font awesome icons. The fit for this library would be when you prioritize speed and size, thus the limitations. 

Another appoach might be to have several components in the library, i.e. 
`Icon` - standard
`SizedIcon` - icon which accepts size property like <SizedIcon size="30px">
and so on... 

For me, I tend to set the size of the icons using CSS

**Comment by moshfeu** [comment]
Thanks for the reply and the reference.
