### ISSUE TITLE
Example Code does not work

### ISSUE THREAD

**Issue by psotos** [alphapeter/fa-svelte#9]
The example that you have in your Readme file does not work for me. It looks like even the path you reference is invalid.

import { faCircle } from '@fortawesome/free-solid-svg-icons/faCircle'
Doesnt match the Node_modules directory structure for your npm module. Can you please help to resolve?

thanks,

**Comment by alphapeter** [comment]
Hi!
The documentation for installing the font awesome fonts is available at https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers  

If using npm, you can run (for the free version)  
`npm install --save-dev @fortawesome/fontawesome-free`  


Do you think I should add a comment about installing font awesome in the readme.md?

**Comment by alphapeter** [comment]
I think there where several different font awesome packages when I wrote the documentation, hence I omitted that part.

**Comment by alphapeter** [comment]
You could also look in the example directory package.json for which npm package I used for the example. 

Int that case I used `@fortawesome/free-solid-svg-icons`

**Comment by psotos** [comment]
NM I got it to work. I had missed the step where I needed to install your version of the font awesome solid icons.

**Comment by psotos** [comment]
> I think there where several different font awesome packages when I wrote the documentation, hence I omitted that part.

I would love to see you update the package to make it more fully featured. It is a great start!
